### ISSUE TITLE
only huge pods on the unlimited branch?

### ISSUE THREAD

**Issue by tchncs** [duane-r/loud_walking#2]
Hi again, i just switched to the unlimited branch and i can't help myself but should all pods be huge now?

Edit: and if this is planned, may you give option for the size?

**Comment by duane-r** [comment]
That's kind of the point. You can make them as big or small as you like and change the space between them. Once I get everything working, I'll put in settings for all the parameters.

**Comment by tchncs** [comment]
Ah, i see, thanks :)

**Comment by tchncs** [comment]
But, just thinking: You announced this mod with the smaller pods and the players really enjoyed it.
May you default to the old sizes again for? It would be awesome because now many players are unhappy. :)

**Comment by duane-r** [comment]
Unlimited is going to have a lot of issues for a while. That's why I made a separate branch for it. It's not ready for general use. I plan to set the default size to 100m horizontally when it's done.
