### ISSUE TITLE
biopods sometimes broken

### ISSUE THREAD

**Issue by tchncs** [duane-r/loud_walking#4]
I just noticed that not all pods are complete:

![screenshot_20170912_105534](https://user-images.githubusercontent.com/10698140/30316939-08a34c42-97a9-11e7-9cde-c619686c74d3.png)

**Comment by tchncs** [comment]
It may become a serious problem when players acting crazy on the server (water) :/ 

![screenshot_20170912_110157](https://user-images.githubusercontent.com/10698140/30317260-e093ef12-97a9-11e7-9f3a-480b3ada3458.png)

**Comment by duane-r** [comment]
That's probably because an error occurred. Instead of crashing, it's just refusing to generate a chunk, but I need to see the error output in the log to know what went wrong.

**Comment by tchncs** [comment]
Okey i enabled verbose and moved a bit in the world.

![2017-09-13-101442_3360x1396_scrot](https://user-images.githubusercontent.com/10698140/30366815-a4ea1c16-986c-11e7-8c5f-c015240e420b.jpg)

This time i used 0.4.16 release instead of 0.5 master.
Here is a log snippet: https://haste.tchncs.de/raw/oqixatoloq

**Comment by duane-r** [comment]
I don't see any generation errors. Are you using a new map or the one where the last errors happened? I can't fill in chunks that have already been generated.

**Comment by tchncs** [comment]
It was the same map but a new area.
Just to be sure i created a new one, i teleported myself right into a pod - it only had some stone on the floor and wasn't filled with any biome and i stopped in a pod where a part of a side was missing.
For me, the log looks quite the same: https://haste.tchncs.de/raw/amesitilem

**Comment by duane-r** [comment]
Well, give me your map seed and I'll try to reproduce it.

**Comment by tchncs** [comment]
Latest one is `14262757497872989606`.
I also have geomoria/integral/underworlds/fun_caves/ethereal active.

Biome params are looking a bit few, here's the whole thing:

```
mg_biome_np_humidity_blend = {
	flags = defaults
	lacunarity = 2
	offset = 0
	scale = 1.5
	spread = (8,8,8)
	seed = 90003
	octaves = 2
	persistence = 1
}
mg_biome_np_humidity = {
	flags = defaults
	lacunarity = 2
	offset = 50
	scale = 50
	spread = (1000,1000,1000)
	seed = 842
	octaves = 3
	persistence = 0.5
}
mg_biome_np_heat_blend = {
	flags = defaults
	lacunarity = 2
	offset = 0
	scale = 1.5
	spread = (8,8,8)
	seed = 13
	octaves = 2
	persistence = 1
}
mg_biome_np_heat = {
	flags = defaults
	lacunarity = 2
	offset = 50
	scale = 50
	spread = (1000,1000,1000)
	seed = 5349
	octaves = 3
	persistence = 0.5
}
seed = 14262757497872989606
water_level = -31000
mapgen_limit = 31000
mg_name = singlenode
chunksize = 5
mg_flags = caves, nodungeons, light, decorations
[end_of_params]
```

**Comment by duane-r** [comment]
Ok, I think I've got it. Try the latest push.

**Comment by tchncs** [comment]
It works just wonderful now, sometimes plants are hovering in the air but this is not a dealbreaker for me - thanks a bunch!
